<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '<?php echo $modelClass; ?>|<?php echo $this->pluralize($modelClass); ?>' => '',
  'Additional Data' => '',
  'Advanced Search' => '',
  'All' => '',
  'Attachment File' => '',
  'Attachment Name' => '',
  'AuthAssignment|AuthAssignments' => '',
  'AuthItemChild|AuthItemChildren' => '',
  'AuthItem|AuthItems' => '',
  'BabyActionCategory|BabyActionCategories' => '',
  'BabyActionLog|BabyActionLogs' => '',
  'Baby|Babies' => '',
  'Banned' => '',
  'Bizrule' => '',
  'Body' => '',
  'Body Alt' => '',
  'Born Date' => '',
  'Color' => '',
  'Content|Contents' => '',
  'Create' => '',
  'Created At' => '',
  'CronMail|CronMails' => '',
  'Data' => '',
  'Delete' => '',
  'Description' => '',
  'Email' => '',
  'Encryption' => '',
  'Extension Handlers' => '',
  'Fields with' => '',
  'From Mail' => '',
  'From Name' => '',
  'Host' => '',
  'ID' => '',
  'Index' => '',
  'Is Active' => '',
  'Is Sent' => '',
  'Key' => '',
  'Last Login' => '',
  'List' => '',
  'Manage' => '',
  'Name' => '',
  'No' => '',
  'Password' => '',
  'Password again' => '',
  'Port' => '',
  'Role' => '',
  'Save' => '',
  'Search' => '',
  'Slug' => '',
  'Smtp|Smtps' => '',
  'Social Service' => '',
  'Subject' => '',
  'Text' => '',
  'Time Finish' => '',
  'Time Start' => '',
  'Timeout' => '',
  'Title' => '',
  'To Mail' => '',
  'To Name' => '',
  'Type' => '',
  'Update' => '',
  'Updated At' => '',
  'User Social' => '',
  'UserSocial|UserSocials' => '',
  'Userid' => '',
  'Username' => '',
  'User|Users' => '',
  'Using Count' => '',
  'View' => '',
  'Yes' => '',
  'Your request is invalid.' => '',
  'are required' => '',
  'password' => '',
  '{$label}' => '',
);
