<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '<?php echo $modelClass; ?>|<?php echo $this->pluralize($modelClass); ?>' => '',
  'Access Control Allow Origin' => '',
  'Additional Data' => '',
  'Advanced Search' => '',
  'All' => 'Все',
  'Application|Applications' => '',
  'Attachment File' => '',
  'Attachment Name' => '',
  'AuthAssignment|AuthAssignments' => '',
  'AuthItemChild|AuthItemChildren' => '',
  'AuthItem|AuthItems' => '',
  'Avatar Name' => '',
  'Banned' => '',
  'Bizrule' => '',
  'Body' => '',
  'Body Alt' => '',
  'Content|Contents' => '',
  'Create' => '',
  'Created At' => '',
  'CronMail|CronMails' => '',
  'Data' => '',
  'Delete' => '',
  'Description' => '',
  'Email' => '',
  'Encryption' => '',
  'Expire At' => '',
  'Extension Handlers' => '',
  'Fields with' => '',
  'First Name' => '',
  'From Mail' => '',
  'From Name' => '',
  'Host' => '',
  'ID' => '',
  'Incorrect tag name' => '',
  'Index' => '',
  'Is Active' => '',
  'Is Sent' => '',
  'Key' => '',
  'Last Login' => '',
  'Last Name' => '',
  'List' => '',
  'Manage' => '',
  'Middle Name' => '',
  'Name' => '',
  'No' => '',
  'Password' => 'Пароль',
  'Port' => 'Порт',
  'Publick Key' => 'ч',
  'Return Uri' => '',
  'Role' => '',
  'Save' => 'Сохранить',
  'Search' => '',
  'Secret Key' => '',
  'Slug' => '',
  'Smtp|Smtps' => '',
  'Social Service' => '',
  'Subject' => '',
  'Text' => '',
  'Timeout' => '',
  'Title' => '',
  'To Mail' => '',
  'To Name' => '',
  'Token' => '',
  'Token|Tokens' => '',
  'Too late to edit this record' => '',
  'Type' => '',
  'Update' => '',
  'Updated At' => '',
  'Url' => '',
  'User Social' => '',
  'UserSocial|UserSocials' => '',
  'Userid' => '',
  'Username' => 'Имя пользователя',
  'User|Users' => 'Пользователь|Пользователя|Пользователей|Пользователя',
  'Using Count' => '',
  'View' => 'Вид',
  'Yes' => 'Да',
  'Your request is invalid.' => '',
  'are required' => 'требуются',
  'password' => 'пароль',
  '{$label}' => '',
);
