<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array(
    'Account has been unbound' => 'Акаунт был отсоединён',
    'Action' => 'Действие',
    'Add' => 'Добавить',
    'Aggregate events' => 'Агрегировать события',
    'All' => 'Все',
    'All period' => 'Весь период',
    'Change email' => 'Изменить email',
    'Changed password' => 'Изменить пароль',
    'Changed username' => 'Изменить Имя пользователя',
    'Check your mailbox for complete email change process' => 'Проверьте почтовый ящик для завершения процесса смены email',
    'Check your mailbox for complete recovery password process' => 'Проверьте почтовый ящик для завершения процесса смены пароля',
    'Check your mailbox for complete registration process' => 'Проверьте почтовый ящик для завершения процесса регистрации',
    'Current password' => 'Текущий пароль',
    'Delete event' => 'Удалить событие',
    'Email has been changed' => 'Email был изменен',
    'Event has been removed successful' => 'Событие было успешно удалено',
    'Event has been saved' => 'Событие было сохранено',
    'Event not found' => 'Событие не найдено',
    'Finish' => 'Окончание',
    'For all site features you should use another browser' => 'Для использования всех возможностей сайта вы должны использовать другой браузер',
    'From date' => 'С даты',
    'Change email address' => 'Изменить email',
    'Login' => 'Вход',
    'Login successful' => 'Вход осуществлён успешно',
    'Logout' => 'Выход',
    'My babies' => 'Мои дети',
    'New password' => 'Новый пароль',
    'New password again' => 'Новый пароль снова',
    'No information about your baby. Check filters or add some events.' => 'Нет информации о вашем ребенке. Проверьти фильтры или добавьте несколько событий.',
    'Note' => 'Замечание',
    'Now you can sign in with your username and NEW password' => 'Теперь вы можете войтис вашим логином и НОВЫМ паролем',
    'Now you can sign in with your username and password' => 'Теперь вы можете войтис вашим логином и паролем',
    'Password has been changed' => 'Пароль был изменен',
    'Profile' => 'Профиль',
    'Recovery password' => 'Восстановить пароль',
    'Register' => 'Регистрация',
    'Resend registration email' => 'Преотправить снова ',
    'Show events' => 'Показать события',
    'Show/hide all events' => 'Показать/Скрыть все события',
    'Start' => 'Начало',
    'Support' => 'Поддержка',
    'To date' => 'До даты',
    'Username has been changed' => 'Имя пользователя было изменено',
    'Verify your email address' => 'Подтвердите ваш email',
    'You can\'t unbind your social account. Set your email address firstly.' => 'Вы не можете открепить ваш социальный акаунт. Сначала установите ваш email.',
    'You can\'t unbind your social account. Set your password firstly.' => 'Вы не можете открепить ваш социальный акаунт. Сначала установите ваш пароль.',
    'You should be authorised to keep your baby in time!' => 'Вы должны быть авторизованы для поддержки вашего ребёнка в графике!',


);
