<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Account has been unbound' => 'Акаунт был отсоединён',
  'Change' => '',
  'Change email' => 'Изменить email',
  'Change email address' => 'Изменить email',
  'Changed email' => '',
  'Changed email verify' => '',
  'Changed password' => 'Изменить пароль',
  'Changed username' => 'Изменить Имя пользователя',
  'Check your mailbox for complete email change process' => 'Проверьте почтовый ящик для завершения процесса смены email',
  'Check your mailbox for complete recovery password process' => 'Проверьте почтовый ящик для завершения процесса смены пароля',
  'Check your mailbox for complete registration process' => 'Проверьте почтовый ящик для завершения процесса регистрации',
  'Content' => '',
  'Current password' => 'Текущий пароль',
  'Current user profile' => '',
  'Email has been changed' => 'Email был изменен',
  'For all site features you should use another browser' => 'Для использования всех возможностей сайта вы должны использовать другой браузер',
  'Home' => '',
  'Incorrect Password' => '',
  'Incorrect username or password.' => '',
  'Login' => 'Вход',
  'Login successful' => 'Вход осуществлён успешно',
  'Logout' => 'Выход',
  'New email' => '',
  'New password' => 'Новый пароль',
  'New password again' => 'Новый пароль снова',
  'Now you can sign in with your username and NEW password' => 'Теперь вы можете войтис вашим логином и НОВЫМ паролем',
  'Now you can sign in with your username and password' => 'Теперь вы можете войтис вашим логином и паролем',
  'OR USE ONE OF YOUR SOCIAL ACCOUNTS' => '',
  'OR USE SIGNUP FORM TO GET NEW ACCOUNT' => '',
  'Password again' => '',
  'Password has been changed' => 'Пароль был изменен',
  'Profile' => 'Профиль',
  'Recovery' => '',
  'Recovery password' => 'Восстановить пароль',
  'Recovery password (new pass)' => '',
  'Register' => 'Регистрация',
  'Registration' => '',
  'Registration(Verify email)' => '',
  'Remember me next time' => '',
  'Resend' => '',
  'Resend registration email' => 'Преотправить снова ',
  'Resend verify eMail' => '',
  'Submit' => '',
  'Support' => 'Поддержка',
  'Username has been changed' => 'Имя пользователя было изменено',
  'Verify your email address' => 'Подтвердите ваш email',
  'You can\'t unbind your social account. Set your email address firstly.' => 'Вы не можете открепить ваш социальный акаунт. Сначала установите ваш email.',
  'You can\'t unbind your social account. Set your password firstly.' => 'Вы не можете открепить ваш социальный акаунт. Сначала установите ваш пароль.',
  'social_account not for current user' => '',
  'social_account not found' => '',
  'unbind' => '',
);
