<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Hello!' => 'Привет!',
  'Please ignore this message if you not sure in future actions.' => 'Пожалуйста, проигнорируйте это сообщение, если не уверены в дальнейших действиях',
  'To complete <b>email change</b> process click this link' => 'Для завершения процесса <b>смены email</b> пройдите по ссылке',
  'To complete <b>password recovery</b> process click this link:' => 'Для завершения процесса <b>восстановления пароля</b> пройдите по ссылке',
  'To complete <b>registration</b> process click this link:' => 'Для завершения процесса <b>регистрации</b> пройдите по ссылке',
  'old email' => 'старый email',
);
