<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Application base path "{path}" is not a valid directory.' => '',
  'Application runtime path "{path}" is not valid. Please make sure it is a directory writable by the Web server process.' => '',
  'EReCaptcha.publicKey must contain your reCAPTCHA public key.' => '',
  'EReCaptchaValidator.privateKey must contain your reCAPTCHA private key.' => '',
  'Extension path "{path}" does not exist.' => '',
  'Property "{class}.{property}" is not defined.' => '',
  'Property "{class}.{property}" is read only.' => '',
  'Solr Document requires a "solr" ASolrConnection application component.' => '',
  'The verification code is incorrect.' => '',
  'Your request is invalid.' => '',
  '{class} does not have attribute "{attribute}".' => '',
);
