<?php

/**
 * This is the model base class for the table "baby_action_category".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "BabyActionCategory".
 *
 * Columns in table "baby_action_category" available as properties of the model,
 * followed by relations of table "baby_action_category" available as properties of the model.
 *
 * @property integer $id
 * @property integer $created_by
 * @property string $title
 * @property string $description
 * @property string $color
 *
 * @property User $createdBy
 * @property BabyActionLog[] $babyActionLogs
 */
abstract class BaseBabyActionCategory extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'baby_action_category';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'BabyActionCategory|BabyActionCategories', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('title', 'required'),
			array('created_by', 'numerical', 'integerOnly'=>true),
			array('title', 'length', 'max'=>256),
			array('color', 'length', 'max'=>8),
			array('description', 'safe'),
			array('created_by, description, color', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, created_by, title, description, color', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'createdBy' => array(self::BELONGS_TO, 'User', 'created_by'),
			'babyActionLogs' => array(self::HAS_MANY, 'BabyActionLog', 'baby_action_category_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'created_by' => null,
			'title' => Yii::t('app', 'Title'),
			'description' => Yii::t('app', 'Description'),
			'color' => Yii::t('app', 'Color'),
			'createdBy' => null,
			'babyActionLogs' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('created_by', $this->created_by);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('color', $this->color, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}