<?php

/**
 * This is the model base class for the table "baby_action_log".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "BabyActionLog".
 *
 * Columns in table "baby_action_log" available as properties of the model,
 * followed by relations of table "baby_action_log" available as properties of the model.
 *
 * @property integer $id
 * @property integer $baby_id
 * @property integer $baby_action_category_id
 * @property string $description
 * @property string $time_start
 * @property string $time_finish
 * @property string $created_at
 *
 * @property Baby $baby
 * @property BabyActionCategory $babyActionCategory
 */
abstract class BaseBabyActionLog extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'baby_action_log';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'BabyActionLog|BabyActionLogs', $n);
	}

	public static function representingColumn() {
		return 'time_start';
	}

	public function rules() {
		return array(
			array('baby_id, time_start, time_finish, created_at', 'required'),
			array('baby_id, baby_action_category_id', 'numerical', 'integerOnly'=>true),
			array('description', 'safe'),
			array('baby_action_category_id, description', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, baby_id, baby_action_category_id, description, time_start, time_finish, created_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'baby' => array(self::BELONGS_TO, 'Baby', 'baby_id'),
			'babyActionCategory' => array(self::BELONGS_TO, 'BabyActionCategory', 'baby_action_category_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'baby_id' => null,
			'baby_action_category_id' => null,
			'description' => Yii::t('app', 'Description'),
			'time_start' => Yii::t('app', 'Time Start'),
			'time_finish' => Yii::t('app', 'Time Finish'),
			'created_at' => Yii::t('app', 'Created At'),
			'baby' => null,
			'babyActionCategory' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('baby_id', $this->baby_id);
		$criteria->compare('baby_action_category_id', $this->baby_action_category_id);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('time_start', $this->time_start, true);
		$criteria->compare('time_finish', $this->time_finish, true);
		$criteria->compare('created_at', $this->created_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}