<?php

/**
 * This is the model base class for the table "user_place".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserPlace".
 *
 * Columns in table "user_place" available as properties of the model,
 * followed by relations of table "user_place" available as properties of the model.
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $name
 * @property string $cx
 * @property string $cy
 * @property string $cx_p_cy
 * @property string $cx_m_cy
 * @property string $created_at
 * @property string $updated_at
 * @property integer $radius
 * @property integer $permissions
 * @property boolean $is_spirit
 *
 * @property User $user
 */
abstract class BaseUserPlace extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'user_place';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserPlace|UserPlaces', $n);
	}

	public static function representingColumn() {
		return 'created_at';
	}

	public function rules() {
		return array(
			array('user_id, cx, cy, cx_p_cy, cx_m_cy, created_at, permissions', 'required'),
			array('user_id, radius, permissions', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>512),
			array('updated_at, is_spirit', 'safe'),
			array('name, updated_at, radius, is_spirit', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, name, cx, cy, cx_p_cy, cx_m_cy, created_at, updated_at, radius, permissions, is_spirit', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'name' => Yii::t('app', 'Name'),
			'cx' => Yii::t('app', 'Cx'),
			'cy' => Yii::t('app', 'Cy'),
			'cx_p_cy' => Yii::t('app', 'Cx P Cy'),
			'cx_m_cy' => Yii::t('app', 'Cx M Cy'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'radius' => Yii::t('app', 'Radius'),
			'permissions' => Yii::t('app', 'Permissions'),
			'is_spirit' => Yii::t('app', 'Is Spirit'),
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('cx', $this->cx, true);
		$criteria->compare('cy', $this->cy, true);
		$criteria->compare('cx_p_cy', $this->cx_p_cy, true);
		$criteria->compare('cx_m_cy', $this->cx_m_cy, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('radius', $this->radius);
		$criteria->compare('permissions', $this->permissions);
		$criteria->compare('is_spirit', $this->is_spirit);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}