<?php

/**
 * This is the model base class for the table "cron_mail".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CronMail".
 *
 * Columns in table "cron_mail" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $subject
 * @property string $body
 * @property string $body_alt
 * @property string $to_mail
 * @property string $to_name
 * @property string $from_mail
 * @property string $from_name
 * @property boolean $is_sent
 * @property string $attachment_file
 * @property string $attachment_name
 *
 */
abstract class BaseCronMail extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cron_mail';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CronMail|CronMails', $n);
	}

	public static function representingColumn() {
		return 'body';
	}

	public function rules() {
		return array(
			array('body, to_mail, from_mail', 'required'),
			array('subject', 'length', 'max'=>255),
			array('to_mail, to_name, from_mail, from_name, attachment_file, attachment_name', 'length', 'max'=>512),
			array('body_alt, is_sent', 'safe'),
			array('subject, body_alt, to_name, from_name, is_sent, attachment_file, attachment_name', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, subject, body, body_alt, to_mail, to_name, from_mail, from_name, is_sent, attachment_file, attachment_name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'subject' => Yii::t('app', 'Subject'),
			'body' => Yii::t('app', 'Body'),
			'body_alt' => Yii::t('app', 'Body Alt'),
			'to_mail' => Yii::t('app', 'To Mail'),
			'to_name' => Yii::t('app', 'To Name'),
			'from_mail' => Yii::t('app', 'From Mail'),
			'from_name' => Yii::t('app', 'From Name'),
			'is_sent' => Yii::t('app', 'Is Sent'),
			'attachment_file' => Yii::t('app', 'Attachment File'),
			'attachment_name' => Yii::t('app', 'Attachment Name'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('subject', $this->subject, true);
		$criteria->compare('body', $this->body, true);
		$criteria->compare('body_alt', $this->body_alt, true);
		$criteria->compare('to_mail', $this->to_mail, true);
		$criteria->compare('to_name', $this->to_name, true);
		$criteria->compare('from_mail', $this->from_mail, true);
		$criteria->compare('from_name', $this->from_name, true);
		$criteria->compare('is_sent', $this->is_sent);
		$criteria->compare('attachment_file', $this->attachment_file, true);
		$criteria->compare('attachment_name', $this->attachment_name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}