<?php

/**
 * This is the model base class for the table "favorite".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Favorite".
 *
 * Columns in table "favorite" available as properties of the model,
 * followed by relations of table "favorite" available as properties of the model.
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $favorite_id
 * @property string $type
 * @property string $created_at
 * @property string $updated_at
 *
 * @property User $user
 */
abstract class BaseFavorite extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'favorite';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Favorite|Favorites', $n);
	}

	public static function representingColumn() {
		return 'created_at';
	}

	public function rules() {
		return array(
			array('user_id, created_at', 'required'),
			array('user_id, favorite_id', 'numerical', 'integerOnly'=>true),
			array('type', 'length', 'max'=>128),
			array('updated_at', 'safe'),
			array('favorite_id, type, updated_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, favorite_id, type, created_at, updated_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'favorite_id' => Yii::t('app', 'Favorite'),
			'type' => Yii::t('app', 'Type'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('favorite_id', $this->favorite_id);
		$criteria->compare('type', $this->type, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}