<?php

/**
 * This is the model base class for the table "user_settings".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserSettings".
 *
 * Columns in table "user_settings" available as properties of the model,
 * followed by relations of table "user_settings" available as properties of the model.
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $radius
 *
 * @property User $user
 */
abstract class BaseUserSettings extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'user_settings';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserSettings|UserSettings', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('user_id', 'required'),
			array('user_id', 'numerical', 'integerOnly'=>true),
			array('radius', 'safe'),
			array('radius', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, radius', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'radius' => Yii::t('app', 'Radius'),
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('radius', $this->radius, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}