<?php

/**
 * This is the model base class for the table "baby".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Baby".
 *
 * Columns in table "baby" available as properties of the model,
 * followed by relations of table "baby" available as properties of the model.
 *
 * @property integer $id
 * @property integer $created_by
 * @property integer $name
 * @property string $born_date
 * @property string $created_at
 *
 * @property User $createdBy
 * @property BabyActionLog[] $babyActionLogs
 */
abstract class BaseBaby extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'baby';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Baby|Babies', $n);
	}

	public static function representingColumn() {
		return 'created_at';
	}

	public function rules() {
		return array(
			array('created_by, created_at', 'required'),
			array('created_by, name', 'numerical', 'integerOnly'=>true),
			array('born_date', 'safe'),
			array('name, born_date', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, created_by, name, born_date, created_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'createdBy' => array(self::BELONGS_TO, 'User', 'created_by'),
			'babyActionLogs' => array(self::HAS_MANY, 'BabyActionLog', 'baby_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'created_by' => null,
			'name' => Yii::t('app', 'Name'),
			'born_date' => Yii::t('app', 'Born Date'),
			'created_at' => Yii::t('app', 'Created At'),
			'createdBy' => null,
			'babyActionLogs' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('created_by', $this->created_by);
		$criteria->compare('name', $this->name);
		$criteria->compare('born_date', $this->born_date, true);
		$criteria->compare('created_at', $this->created_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}