<?php

/**
 * This is the model base class for the table "tag_post".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TagPost".
 *
 * Columns in table "tag_post" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $post_id
 * @property integer $tag_id
 *
 */
abstract class BaseTagPost extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tag_post';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TagPost|TagPosts', $n);
	}

	public static function representingColumn() {
		return array(
			'post_id',
			'tag_id',
		);
	}

	public function rules() {
		return array(
			array('post_id, tag_id', 'required'),
			array('post_id, tag_id', 'numerical', 'integerOnly'=>true),
			array('post_id, tag_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'post_id' => null,
			'tag_id' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('post_id', $this->post_id);
		$criteria->compare('tag_id', $this->tag_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}