<?php

/**
 * This is the model base class for the table "application".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Application".
 *
 * Columns in table "application" available as properties of the model,
 * followed by relations of table "application" available as properties of the model.
 *
 * @property integer $id
 * @property string $slug
 * @property string $name
 * @property string $description
 * @property string $secret_key
 * @property string $publick_key
 * @property string $return_uri
 * @property string $access_control_allow_origin
 * @property string $created_at
 * @property string $updated_at
 * @property boolean $is_active
 *
 * @property Token[] $tokens
 */
abstract class BaseApplication extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'application';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Application|Applications', $n);
	}

	public static function representingColumn() {
		return 'slug';
	}

	public function rules() {
		return array(
			array('slug, name, secret_key, publick_key, created_at', 'required'),
			array('slug, secret_key, publick_key', 'length', 'max'=>128),
			array('name, return_uri', 'length', 'max'=>512),
			array('description, access_control_allow_origin, updated_at, is_active', 'safe'),
			array('description, return_uri, access_control_allow_origin, updated_at, is_active', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, slug, name, description, secret_key, publick_key, return_uri, access_control_allow_origin, created_at, updated_at, is_active', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'tokens' => array(self::HAS_MANY, 'Token', 'application_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'slug' => Yii::t('app', 'Slug'),
			'name' => Yii::t('app', 'Name'),
			'description' => Yii::t('app', 'Description'),
			'secret_key' => Yii::t('app', 'Secret Key'),
			'publick_key' => Yii::t('app', 'Publick Key'),
			'return_uri' => Yii::t('app', 'Return Uri'),
			'access_control_allow_origin' => Yii::t('app', 'Access Control Allow Origin'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'is_active' => Yii::t('app', 'Is Active'),
			'tokens' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('slug', $this->slug, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('secret_key', $this->secret_key, true);
		$criteria->compare('publick_key', $this->publick_key, true);
		$criteria->compare('return_uri', $this->return_uri, true);
		$criteria->compare('access_control_allow_origin', $this->access_control_allow_origin, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('is_active', $this->is_active);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}