<?php

/**
 * This is the model base class for the table "user_feed_external".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserFeedExternal".
 *
 * Columns in table "user_feed_external" available as properties of the model,
 * followed by relations of table "user_feed_external" available as properties of the model.
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $last_published_id
 * @property integer $feed_external_id
 * @property string $created_at
 * @property string $updated_at
 *
 * @property User $user
 * @property FeedExternal $feedExternal
 */
abstract class BaseUserFeedExternal extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'user_feed_external';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserFeedExternal|UserFeedExternals', $n);
	}

	public static function representingColumn() {
		return 'created_at';
	}

	public function rules() {
		return array(
			array('user_id, feed_external_id, created_at', 'required'),
			array('user_id, last_published_id, feed_external_id', 'numerical', 'integerOnly'=>true),
			array('updated_at', 'safe'),
			array('last_published_id, updated_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, last_published_id, feed_external_id, created_at, updated_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
			'feedExternal' => array(self::BELONGS_TO, 'FeedExternal', 'feed_external_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'last_published_id' => Yii::t('app', 'Last Published'),
			'feed_external_id' => null,
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'user' => null,
			'feedExternal' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('last_published_id', $this->last_published_id);
		$criteria->compare('feed_external_id', $this->feed_external_id);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}