<?php

/**
 * This is the model base class for the table "tag_place".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TagPlace".
 *
 * Columns in table "tag_place" available as properties of the model,
 * followed by relations of table "tag_place" available as properties of the model.
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $tag_id
 * @property string $created_at
 * @property string $updated_at
 * @property string $cx
 * @property string $cy
 * @property string $cx_p_cy
 * @property string $cx_m_cy
 *
 * @property Tag $tag
 * @property User $user
 */
abstract class BaseTagPlace extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tag_place';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TagPlace|TagPlaces', $n);
	}

	public static function representingColumn() {
		return 'created_at';
	}

	public function rules() {
		return array(
			array('user_id, tag_id, created_at, cx, cy, cx_p_cy, cx_m_cy', 'required'),
			array('user_id, tag_id', 'numerical', 'integerOnly'=>true),
			array('updated_at', 'safe'),
			array('updated_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, tag_id, created_at, updated_at, cx, cy, cx_p_cy, cx_m_cy', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'tag' => array(self::BELONGS_TO, 'Tag', 'tag_id'),
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'tag_id' => null,
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'cx' => Yii::t('app', 'Cx'),
			'cy' => Yii::t('app', 'Cy'),
			'cx_p_cy' => Yii::t('app', 'Cx P Cy'),
			'cx_m_cy' => Yii::t('app', 'Cx M Cy'),
			'tag' => null,
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('tag_id', $this->tag_id);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('cx', $this->cx, true);
		$criteria->compare('cy', $this->cy, true);
		$criteria->compare('cx_p_cy', $this->cx_p_cy, true);
		$criteria->compare('cx_m_cy', $this->cx_m_cy, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}