<?php

/**
 * This is the model base class for the table "smtp".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Smtp".
 *
 * Columns in table "smtp" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $host
 * @property string $username
 * @property string $password
 * @property string $port
 * @property string $encryption
 * @property string $timeout
 * @property string $extensionHandlers
 * @property integer $using_count
 * @property integer $banned
 *
 */
abstract class BaseSmtp extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'smtp';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Smtp|Smtps', $n);
	}

	public static function representingColumn() {
		return 'host';
	}

	public function rules() {
		return array(
			array('host, username, password', 'required'),
			array('using_count, banned', 'numerical', 'integerOnly'=>true),
			array('port, encryption, timeout, extensionHandlers', 'safe'),
			array('port, encryption, timeout, extensionHandlers, using_count, banned', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, host, username, password, port, encryption, timeout, extensionHandlers, using_count, banned', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'host' => Yii::t('app', 'Host'),
			'username' => Yii::t('app', 'Username'),
			'password' => Yii::t('app', 'Password'),
			'port' => Yii::t('app', 'Port'),
			'encryption' => Yii::t('app', 'Encryption'),
			'timeout' => Yii::t('app', 'Timeout'),
			'extensionHandlers' => Yii::t('app', 'Extension Handlers'),
			'using_count' => Yii::t('app', 'Using Count'),
			'banned' => Yii::t('app', 'Banned'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('host', $this->host, true);
		$criteria->compare('username', $this->username, true);
		$criteria->compare('password', $this->password, true);
		$criteria->compare('port', $this->port, true);
		$criteria->compare('encryption', $this->encryption, true);
		$criteria->compare('timeout', $this->timeout, true);
		$criteria->compare('extensionHandlers', $this->extensionHandlers, true);
		$criteria->compare('using_count', $this->using_count);
		$criteria->compare('banned', $this->banned);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}