<?php

/**
 * This is the model base class for the table "user_social".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserSocial".
 *
 * Columns in table "user_social" available as properties of the model,
 * followed by relations of table "user_social" available as properties of the model.
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $social_service
 * @property string $user_social_id
 * @property string $additional_data
 *
 * @property User $user
 */
abstract class BaseUserSocial extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'user_social';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserSocial|UserSocials', $n);
	}

	public static function representingColumn() {
		return 'social_service';
	}

	public function rules() {
		return array(
			array('user_id, social_service, user_social_id', 'required'),
			array('user_id', 'numerical', 'integerOnly'=>true),
			array('additional_data', 'safe'),
			array('additional_data', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, social_service, user_social_id, additional_data', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'social_service' => Yii::t('app', 'Social Service'),
			'user_social_id' => Yii::t('app', 'User Social'),
			'additional_data' => Yii::t('app', 'Additional Data'),
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('social_service', $this->social_service, true);
		$criteria->compare('user_social_id', $this->user_social_id, true);
		$criteria->compare('additional_data', $this->additional_data, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}